[package]
name = "pwtool"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.59", features = ["derive"] }
cli-clipboard = "=0.4.0"
csv = "1.4.0"
magic-crypt = "5.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.150"
toml = "1.0"
uuid = { version = "1.24.0", features = ["v4"] }

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
assert_fs = "1.1.1"
