#keep the vault_path as 'test-sample.json' for tests
password_vault_path = "test-sample.json"
vault_file_type = "json"
encryption_key = "magickey"

[auto_generated_pws]
word_length = 2
items = [
    "santA1.",
    "k3kkoneN!",
    "autob4HN=",
]